[package]
name = "canvas"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
glam = { workspace = true }
gpui = { workspace = true }
node = { path = "../node" }
theme = { path = "../theme" }
serde = { workspace = true }
uuid = { workspace = true }
