[package]
name = "interchange"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
kdl = { workspace = true }
node_2 = { path = "../node_2" }
glam = { workspace = true }
gpui = { workspace = true }
uuid = { workspace = true }
