[package]
name = "interchange"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
kdl = { workspace = true }
node = { path = "../node" }
glam = { workspace = true }
gpui = { workspace = true }
uuid = { workspace = true }
