[package]
name = "api"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
canvas = { path = "../canvas" }
glam.workspace = true
gpui.workspace = true
node = { path = "../node" }
serde.workspace = true
serde_json.workspace = true
