[package]
name = "api"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
glam.workspace = true
gpui.workspace = true
node_2 = { path = "../node_2" }
serde.workspace = true
serde_json.workspace = true
