[package]
name = "node_2"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
glam = { workspace = true }
gpui = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
